### ISSUE TITLE
Latest release (0.5.2) in mvn central is missing latest changes

### ISSUE THREAD

**Issue by ninjaMikeG** [RohanNagar/op-connect-sdk-java#127]
The latest version in mvn central is 0.5.2, but does not include your changes to fix: 
` com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "name" (class com.sanctionco.opconnect.model.Id), not marked as ignorable (one known property: "id"])
`
This was commit `c1b9cc4` back in may 2022. Do you have plans to release this fix into central?

🙏

**Comment by RohanNagar** [comment]
@ninjaMikeG thank you for opening this issue and for the nudge!

I just released `0.5.3`, which should be in Maven Central within 10 minutes. Please let me know if you run into any issues with this version.
