### ISSUE TITLE
Include op-connect-sdk-java in 1Password Community Project Showcase

### ISSUE THREAD

**Issue by techcraver** [RohanNagar/op-connect-sdk-java#134]
👋
I'm Jason, a Developer Evangelist at 1Password. On our [Developer Portal](https://developer.1password.com/), we have a place where we [showcase community projects](https://developer.1password.com/community) that are built with or on 1Password's Developer Tools.

We'd love to feature your repo! Would you be up for [submitting](https://github.com/1Password/developer-community-projects/pulls) a PR?

**Comment by RohanNagar** [comment]
Hi @techcraver thanks for reaching out! I'd love for the Java SDK to be featured on the showcase. I have submitted https://github.com/1Password/developer-community-projects/pull/8 to the repo for consideration.

**Comment by techcraver** [comment]
Awesome! I see the PR. Thanks!
