### ISSUE TITLE
URL Object Serialization

### ISSUE THREAD

**Issue by Christianuss** [RohanNagar/op-connect-sdk-java#5]
https://github.com/RohanNagar/op-connect-sdk-java/blob/73ba2c02cab022769389a5c92c582e2704b09d04/src/main/java/com/sanctionco/opconnect/model/URL.java#L13-L22

I think Jackson uses the getter here to serialize the object. Even though the [docs](https://support.1password.com/connect-api-reference/#url-object) state the field name is `url`, it seems to be `href` in both directions. Which means URLs are currently empty when adding new items.

Annotating the getter with `@JsonProperty("href")` should probably work.

**Comment by RohanNagar** [comment]
Fixed in 4ff7534
